name: 打包和部署官网

on:
  push:
    branches: ["main"]

env:
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@master

      - name: 安装Node
        uses: actions/setup-node@main
        with:
          node-version: "22.x"

      - name: 安装依赖
        run: pnpm i

      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete --mkpath"
          SOURCE: "/"
          EXCLUDE: '/node_modules/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: root
          TARGET: /home/apps-root/${{ env.PROJECT_NAME }}/
          SCRIPT_AFTER: |
            cd /home/apps-root/${{ env.PROJECT_NAME }}
            pnpm i
            pm2 list | grep -q "${{ env.PROJECT_NAME }}" && pm2 delete ${{ env.PROJECT_NAME }}
            pm2 start "npm run start" --name ${{ env.PROJECT_NAME }}
                